<?php

namespace AppBundle\Repository;

/**
 * PanelProductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanelProductionRepository extends \Doctrine\ORM\EntityRepository
{
}
